
name: Pull Request

on:
  # Always build pull requests
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Build PR
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1

      - name: Retrieve formula name
        id: retrieve_formula_name
        run: |
          FORMULA=$(./linux/get-formula-from-pr-contents.sh "${GITHUB_REPOSITORY}" "${{ github.event.pull_request.number }}")
          echo ::set-output name=FORMULA::${FORMULA}

      - name: Install Linuxbrew
        run: |
          sudo apt-get update && sudo apt-get -y install jq

          # Hack: Remove all files from /usr/local/include as any files there which have not been
          #  installed by linuxbrew will make `brew doctor` produce warnings
          sudo rm -rf /usr/local/include

          source ./linux/install-linuxbrew.sh

          echo "::set-env name=HOMEBREW_PREFIX::${HOMEBREW_PREFIX}"
          echo "::set-env name=HOMEBREW_CELLAR::${HOMEBREW_CELLAR}"
          echo "::set-env name=HOMEBREW_REPOSITORY::${HOMEBREW_REPOSITORY}"
          echo "::add-path::${HOMEBREW_PREFIX}/bin"
          echo "::add-path::${HOMEBREW_PREFIX}/sbin"

          echo "Current permissions, Formula:"
          ls -l Formula
          echo "Current permissions, /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps:"
          ls -l /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps

          # Hack: change permissions for library from 666 to 644 since the umask is not honored
          #  yet 'brew audit' requires 644 for the formula file on Linux
          # We change permissions for all taps, since brew will lowercase org folder names, so
          #  ...SOURCE_ORGANIZATION is not necessarily a valid folder name
          chmod -R go-w /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps

      - name: Install current PR as tap
        run: |
          GITHUB_TAP_ORGANIZATION="kalmalyzer"
          GITHUB_TAP_REPOSITORY="homebrew-prebuilt-amiga-dev-tools"
          HOMEBREW_TAP_DIR="/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/${GITHUB_TAP_ORGANIZATION}/${GITHUB_TAP_REPOSITORY}"
          mkdir -p "${HOMEBREW_TAP_DIR}"
          rm -rf "${HOMEBREW_TAP_DIR}"
          ln -s "${PWD}" "${HOMEBREW_TAP_DIR}"

          echo "Current permissions, /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/:"
          ls -l /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/
          echo "Current permissions, /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/kalmalyzer/:"
          ls -l /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/kalmalyzer/
          echo "Current permissions, /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/kalmalyzer/homebrew-prebuilt-amiga-dev-tools/:"
          ls -l /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/kalmalyzer/homebrew-prebuilt-amiga-dev-tools/
          echo "Current permissions, /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/kalmalyzer/homebrew-prebuilt-amiga-dev-tools/Formula/:"
          ls -l /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/kalmalyzer/homebrew-prebuilt-amiga-dev-tools/Formula/

      - name: Run brew test-bot
        run: |
          HOMEBREW_DEVELOPER=1
          HOMEBREW_NO_AUTO_UPDATE=1
          HOMEBREW_NO_EMOJI=1
          HOMEBREW_FAIL_LOG_LINES=150
          HOMEBREW_COLOR=1
          brew test-bot --verbose ${{ steps.retrieve_formula_name.outputs.FORMULA }}
